{
 "title": "SCiSupplier Containers JMX Overview",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [ "prometheus" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(up{job=~\".*scisupplier.*\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (java_lang_OperatingSystem_FreePhysicalMemorySize{job=~\"$job\"} / on(job) java_lang_OperatingSystem_TotalPhysicalMemorySize{job=~\"$job\"} *100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (java_lang_OperatingSystem_FreeSwapSpaceSize{job=~\"$job\"} / on(job) java_lang_OperatingSystem_TotalSwapSpaceSize{job=~\"$job\"} * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalSwapSpaceSize{job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load(1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{job=~\"$job\"}[1m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load(5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{job=~\"$job\"}[5m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{job=~\"$job\"} * 100",
     "legendFormat": "system"
    },
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{job=~\"$job\"} * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{job=~\"$job\"}  / ignoring(area) group_left java_lang_Memory_HeapMemoryUsage_max{job=~\"$job\"} *100",
     "legendFormat": "Heap"
    }
   ]
  },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pool}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=~\"$job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=~\"$job\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{job=~\"$job\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "Current Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 11 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Current NonHeap Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 11 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{job=~\"$job\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Current Heap + NonHeap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 14 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{job=\"$job\"} + java_lang_Memory_HeapMemoryUsage_used{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Total Heap Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 15 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Heap / NonHeap Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{job=~\"$job\"}",
     "legendFormat": "NonHeap Used"
    },
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{job=~\"$job\"}",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{job=~\"$job\"} + java_lang_Memory_HeapMemoryUsage_used{job=~\"$job\"}",
     "legendFormat": "Combined"
    }
   ]
  },
  {
   "title": "GC time / 2 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"$job\"}[2m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=~\"$job\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}